#!/bin/sh
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Copyright (c) 2013 by Delphix. All rights reserved.
#

#
# This script launches the example server using the JARs from the build
# process. This should eventually be replaced by a more robust launcher that is
# part of the toolkit we copy over to database environments.
#

dirname=$(dirname $0)

cp=$dirname/../../../lib/spring-framework/spring-beans-4.0.2.RELEASE.jar
cp+=:$dirname/../../../lib/spring-framework/spring-context-4.0.2.RELEASE.jar
cp+=:$dirname/../../../lib/spring-framework/spring-core-4.0.2.RELEASE.jar
cp+=:$dirname/../../../lib/spring-framework/spring-aop-4.0.2.RELEASE.jar
cp+=:$dirname/../../../lib/spring-framework/spring-expression-4.0.2.RELEASE.jar
cp+=:$dirname/../../../lib/commons/commons-lang-2.4.jar
cp+=:$dirname/../../../lib/commons/commons-logging-1.1.1.jar
cp+=:$dirname/../../../lib/commons/commons-validator-1.4.0.jar
cp+=:$dirname/../../../lib/guava/guava-15.0.jar
cp+=:$dirname/../../../lib/log4j/log4j-1.2.16.jar
cp+=:$dirname/../../../lib/lz4/lz4-java-1.0.jar
cp+=:$dirname/../../../lib/netty/netty-3.6.3.Final.jar
cp+=:$dirname/../../../bin/jar/platform/platform_all-1.0.0.jar
cp+=:$dirname/../../../bin/jar/logger/logger_all-1.0.0.jar
cp+=:$dirname/../../../bin/jar/exception/exception_all-1.0.0.jar
cp+=:$dirname/../../../bin/jar/session/session_all-1.0.0.jar
cp+=:$dirname/../../../bin/jar/remote/remote_all-1.0.0.jar
cp+=:$dirname/../../../bin/jar/example-server/example-server_all-1.0.0.jar

#
# DSP requires Java assertions to be enabled.
#
exec java -ea -cp $cp -Dlog.dir="log" com/delphix/appliance/host/example/server/ExampleServerLauncher
